server:
  port: 8000
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customers
    username: ${DOCKER_DB_USERNAME}
    password: ${DOCKER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true